@extends('layouts.app')
@section('title', 'Pembetulan Kehadiran')
@section('page-title', 'Pembetulan Kehadiran')
@section('page-subtitle', 'Semak dan putuskan permohonan pembetulan daripada pekerja.')
@section('content')
    @include('attendance.partials.styles')
    <div class="attendance-page"><header class="attendance-head"><div><span class="attendance-kicker">SMART ATTENDANCE</span><h1>Pembetulan Kehadiran</h1><p>Semak permohonan pembetulan dan putuskan sama ada rekod perlu dikemas kini.</p></div><div class="attendance-head__meta"><span>Semakan</span><strong>Admin Attendance</strong></div></header><nav class="attendance-nav"><a href="{{ route('admin.attendance.live') }}">Live Attendance</a><a href="{{ route('admin.attendance.records') }}">Rekod Kehadiran</a></nav>
        <section class="attendance-panel"><form class="attendance-toolbar" method="GET"><label>Status<select name="status"><option value="pending" @selected($status === 'pending')>Pending</option><option value="approved" @selected($status === 'approved')>Diluluskan</option><option value="rejected" @selected($status === 'rejected')>Ditolak</option></select></label><button class="attendance-primary" type="submit">Tapis</button></form><div class="attendance-table-wrap"><table class="attendance-table"><thead><tr><th>Pekerja</th><th>Tarikh</th><th>Jenis</th><th>Masa Dimohon</th><th>Sebab</th><th>Dokumen</th><th>Status</th><th>Tindakan</th></tr></thead><tbody>@forelse($corrections as $correction)<tr><td class="attendance-person"><strong>{{ $correction->staff?->nama }}</strong><span>{{ $correction->staff?->no_pekerja }}</span></td><td>{{ $correction->correction_date->format('d/m/Y') }}</td><td>{{ $correctionTypes[$correction->correction_type] ?? $correction->correction_type }}</td><td>{{ $correction->requested_time?->format('h:i A') ?? '-' }}</td><td>{{ $correction->reason }}</td><td>@if($correction->supporting_document)<a class="attendance-secondary" href="{{ route('admin.attendance.corrections.document', $correction) }}">Buka</a>@else - @endif</td><td><span class="attendance-badge attendance-badge--{{ $correction->status }}">{{ ucfirst($correction->status) }}</span></td><td>@if($correction->status === 'pending')<form method="POST" action="{{ route('admin.attendance.corrections.review', $correction) }}" class="attendance-inline">@csrf @method('PUT')<input type="text" name="admin_remark" placeholder="Catatan admin"><button class="attendance-primary" name="decision" value="approved" type="submit">Lulus</button><button class="attendance-danger" name="decision" value="rejected" type="submit">Tolak</button></form>@else<span>{{ $correction->admin_remark ?? '-' }}</span>@endif</td></tr>@empty<tr><td colspan="8" class="attendance-empty">Tiada permohonan pembetulan untuk status ini.</td></tr>@endforelse</tbody></table></div>@if($corrections->hasPages())<div class="pagination">{{ $corrections->links() }}</div>@endif</section>
    </div>
@endsection
