@extends('layouts.app')
@section('title', 'Rekod Kehadiran')
@section('page-title', 'Rekod Kehadiran')
@section('page-subtitle', 'Semak semua rekod Smart Attendance Pekerja Koperasi.')
@section('content')
    @include('attendance.partials.styles')
    @php $duration = fn ($minutes) => intdiv((int) ($minutes ?? 0), 60).' jam '.((int) ($minutes ?? 0) % 60).' minit'; @endphp
    <div class="attendance-page"><header class="attendance-head"><div><span class="attendance-kicker">SMART ATTENDANCE</span><h1>Rekod Kehadiran</h1><p>Gunakan penapis untuk mencari rekod check in dan check out dengan cepat.</p></div><div class="attendance-head__meta"><span>Modul</span><strong>Smart Attendance</strong></div></header><nav class="attendance-nav"><a href="{{ route('admin.attendance.live') }}">Live Attendance</a><a href="{{ route('admin.attendance.reports') }}">Laporan</a><a href="{{ route('admin.attendance.settings') }}">Tetapan</a></nav>
        <section class="attendance-panel"><form class="attendance-toolbar" method="GET"><label>Tarikh<input type="date" name="date" value="{{ $filters['date'] }}"></label><label>Bulan<input type="month" name="month" value="{{ $filters['month'] }}"></label><label>Pekerja<select name="staff_id"><option value="">Semua pekerja</option>@foreach($workers as $worker)<option value="{{ $worker->id_pekerja }}" @selected($filters['staff_id'] == $worker->id_pekerja)>{{ $worker->nama }} ({{ $worker->no_pekerja }})</option>@endforeach</select></label><label>Status<select name="status"><option value="">Semua status</option>@foreach($statuses as $key=>$label)<option value="{{ $key }}" @selected($filters['status'] === $key)>{{ $label }}</option>@endforeach</select></label><button class="attendance-primary" type="submit">Tapis</button></form>
            <div class="attendance-table-wrap"><table class="attendance-table"><thead><tr><th>Staff</th><th>Tarikh</th><th>Check In</th><th>Check Out</th><th>Lewat</th><th>Keluar Awal</th><th>Jumlah Jam</th><th>Status</th><th>GPS</th><th></th></tr></thead><tbody>@forelse($records as $record)<tr><td class="attendance-person"><strong>{{ $record->staff?->nama }}</strong><span>{{ $record->staff?->no_pekerja }}</span></td><td>{{ $record->attendance_date->format('d/m/Y') }}</td><td>{{ $record->check_in_time?->timezone('Asia/Kuala_Lumpur')->format('h:i A') ?? '-' }}</td><td>{{ $record->check_out_time?->timezone('Asia/Kuala_Lumpur')->format('h:i A') ?? '-' }}</td><td>{{ $record->check_in_time ? $duration($record->late_minutes) : '-' }}</td><td>{{ $record->check_out_time ? $duration($record->early_leave_minutes) : '-' }}</td><td>{{ $record->check_in_time ? $duration($record->working_minutes) : '-' }}</td><td><span class="attendance-badge attendance-badge--{{ $record->status }}">{{ $statuses[$record->status] ?? $record->status }}</span></td><td>{{ $record->check_in_gps_verified ? 'Disahkan' : 'Tidak' }}</td><td><div class="attendance-actions"><a class="attendance-secondary" href="{{ route('admin.attendance.show', $record) }}">Lihat</a><form method="POST" action="{{ route('admin.attendance.destroy', $record) }}" onsubmit="return confirm('Padam rekod kehadiran ini?');">@csrf @method('DELETE')<button class="attendance-danger" type="submit">Delete</button></form></div></td></tr>@empty<tr><td colspan="10" class="attendance-empty">Tiada rekod ditemui.</td></tr>@endforelse</tbody></table></div>@if($records->hasPages())<div class="pagination">{{ $records->links() }}</div>@endif</section>
    </div>
@endsection
