@extends('layouts.app')
@section('title', 'Laporan Kehadiran')
@section('page-title', 'Laporan Kehadiran')
@section('page-subtitle', 'Analisis rekod attendance dan export CSV mengikut pilihan penapis.')
@section('content')
    @include('attendance.partials.styles')
    @php $duration = fn ($minutes) => intdiv((int) ($minutes ?? 0), 60).' jam '.((int) ($minutes ?? 0) % 60).' minit'; @endphp
    <div class="attendance-page"><header class="attendance-head"><div><span class="attendance-kicker">KEHADIRAN PEKERJA</span><h1>Laporan Kehadiran</h1><p>Jana laporan kehadiran mengikut tarikh, pekerja dan status untuk semakan pentadbiran.</p></div><div class="attendance-head__meta"><span>Output</span><strong>CSV & Ringkasan</strong></div></header>
        <section class="attendance-panel"><form class="attendance-toolbar" method="GET"><label>Dari<input type="date" name="from" value="{{ $filters['from'] }}"></label><label>Hingga<input type="date" name="to" value="{{ $filters['to'] }}"></label><label>Pekerja<select name="staff_id"><option value="">Semua pekerja</option>@foreach($workers as $worker)<option value="{{ $worker->id_pekerja }}" @selected($filters['staff_id'] == $worker->id_pekerja)>{{ $worker->nama }}</option>@endforeach</select></label><label>Status<select name="status"><option value="">Semua status</option>@foreach($statuses as $key=>$label)<option value="{{ $key }}" @selected($filters['status'] === $key)>{{ $label }}</option>@endforeach</select></label><button class="attendance-primary" type="submit">Jana Laporan</button><a class="attendance-secondary" href="{{ route('admin.attendance.reports.export', request()->query()) }}" download>Export CSV</a></form><div class="attendance-summary"><div><span>Jumlah Rekod</span><strong>{{ $summary['records'] }}</strong></div><div><span>Hadir</span><strong>{{ $summary['present'] }}</strong></div><div><span>Lewat / Keluar Awal</span><strong>{{ $summary['late'] + $summary['early_leave'] }}</strong></div><div><span>Jumlah Jam Bekerja</span><strong>{{ $duration($summary['working_minutes']) }}</strong></div></div><div class="attendance-table-wrap"><table class="attendance-table"><thead><tr><th>Staff</th><th>Tarikh</th><th>Check In</th><th>Check Out</th><th>Status</th><th>Jam Bekerja</th></tr></thead><tbody>@forelse($records as $record)<tr><td>{{ $record->staff?->nama }} <small>{{ $record->staff?->no_pekerja }}</small></td><td>{{ $record->attendance_date->format('d/m/Y') }}</td><td>{{ $record->check_in_time?->timezone('Asia/Kuala_Lumpur')->format('h:i A') ?? '-' }}</td><td>{{ $record->check_out_time?->timezone('Asia/Kuala_Lumpur')->format('h:i A') ?? '-' }}</td><td>{{ $statuses[$record->status] ?? $record->status }}</td><td>{{ $duration($record->working_minutes) }}</td></tr>@empty<tr><td colspan="6" class="attendance-empty">Tiada data bagi laporan ini.</td></tr>@endforelse</tbody></table></div></section>
    </div>
@endsection
